### ISSUE TITLE
[Inquiry for train dataset generation procedure]

### ISSUE THREAD

**Issue by quito418** [HKU-BAL/ClairS#17]
Hi ClairS team, 

Do you have plan for providing document for training dataset generation? (like in [Clair3](https://github.com/HKU-BAL/Clair3/blob/main/docs/full_alignment_training_r1.md))

Thanks!

**Comment by aquaskyline** [comment]
Yes, but not soon because, at the moment, many validations and optimizations are going on our sides and at our collaborators. Different from Clair3, ClairS is more clinically relevant, thus we expect to be more confident before we can release the training data generating scripts. Nevertheless, the data generation procedures were elaborated in ClairS' preprint.

**Comment by quito418** [comment]
Thank you for the reply, I look forward to it!
