### ISSUE TITLE
Question: Distributing ClairS

### ISSUE THREAD

**Issue by dmaziec** [HKU-BAL/ClairS#43]
Hello,

Thank you so much for implementing ClairS! :) 

I have a question about running ClairS on WGS data. To reduce runtime, I’d like to run ClairS independently on each genomic interval and then merge the results into a single VCF file. Would this approach impact the final variant set, or is there another way to optimize runtime?

Thank you again,
Dominika

**Comment by aquaskyline** [comment]
It won't impact the final variant set as long as your intervals are not overlapping with each other.

For performance, you will need to adjust the `--chunk_size` accordingly. Say if you set `--thread 32` for each 5Mbp interval on a single computing node. The best chuck_size is calculated as 5Mbp/32*4, the constant 4 is because ClairS uses 4 threads for each chunk.
